Change to notify instead of subscribe
After making the module compatible with puppetlabs/concat,
subscribing to the config file failed with:

    Error: Failed to apply catalog: Could not find dependency
      File[/etc/unbound/unbound.conf] for Service[unbound]
      at /etc/puppet/modules/unbound/manifests/service.pp:21

So we use notify now from every concat::fragment